### Обучающая и тестовая выборки

- В качестве обучающей выборки будем использовать наборы, полученные при помощи train_test_split из scikit-learn.
- Конечно, алгоритм может работать с многомерным пространством, но для удобства демонстраиции алгоритма мы используем двухмерный набор данных.
- Если разные признаки имеют сильно отличающиеся диапазоны значений, то применяют масштабирование исходных данных.

In [93]:
# Установим необходимые библиотеки (раскоментировать)
#%pip install numpy pandas sklearn

In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [95]:
data_full = pd.read_csv('data/dataset.csv', sep=",")
data_full

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,0.00,1.000,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.00,yes,no,3.0,3.0,Sometimes,yes,3.00,yes,3.00,0.000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,2.00,1.000,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.00,no,no,3.0,3.0,Sometimes,no,2.00,no,2.00,0.000,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.80,no,no,2.0,1.0,Sometimes,no,2.00,no,0.00,0.000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21,1.71,131.41,yes,yes,3.0,3.0,Sometimes,no,1.73,no,1.68,0.906,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22,1.75,133.74,yes,yes,3.0,3.0,Sometimes,no,2.01,no,1.34,0.599,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23,1.75,133.69,yes,yes,3.0,3.0,Sometimes,no,2.05,no,1.41,0.646,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24,1.74,133.35,yes,yes,3.0,3.0,Sometimes,no,2.85,no,1.14,0.586,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24,1.74,133.47,yes,yes,3.0,3.0,Sometimes,no,2.86,no,1.03,0.714,Sometimes,Public_Transportation,Obesity_Type_III

Проверим датасет на пустые значения.

In [96]:
# проверим есть ли пропущенные значения
data_full.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

Заметим, что NObeyesdad является категориальным признаком, рассмотрим уникальные значения для него:

In [97]:
np.unique(data_full[['NObeyesdad']])

array(['Insufficient_Weight', 'Normal_Weight', 'Obesity_Type_I',
       'Obesity_Type_II', 'Obesity_Type_III', 'Overweight_Level_I',
       'Overweight_Level_II'], dtype=object)

Приведем признак к нумерическому типу.

In [98]:
def target_to_regr(target: str) -> float:
    mapping = {
        'Insufficient_Weight': 0,
        'Normal_Weight': 0,
        'Overweight_Level_I': 1,
        'Overweight_Level_II': 1,
        'Obesity_Type_I': 1,
        'Obesity_Type_II': 1,
        'Obesity_Type_III': 1
    }
    return mapping.get(target, 2)  # Возвращает 2, если категория не найдена

In [99]:
# Для начала, преобразуем целевой признак в категориальный для примера
data_full['Obesity'] = \
data_full.apply(lambda row: target_to_regr(row['NObeyesdad']),axis=1)
data_full=data_full.drop(columns='NObeyesdad')
data_full

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21,1.62,64.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,0.00,1.000,no,Public_Transportation,0
1,Female,21,1.52,56.00,yes,no,3.0,3.0,Sometimes,yes,3.00,yes,3.00,0.000,Sometimes,Public_Transportation,0
2,Male,23,1.80,77.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,2.00,1.000,Frequently,Public_Transportation,0
3,Male,27,1.80,87.00,no,no,3.0,3.0,Sometimes,no,2.00,no,2.00,0.000,Frequently,Walking,1
4,Male,22,1.78,89.80,no,no,2.0,1.0,Sometimes,no,2.00,no,0.00,0.000,Sometimes,Public_Transportation,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21,1.71,131.41,yes,yes,3.0,3.0,Sometimes,no,1.73,no,1.68,0.906,Sometimes,Public_Transportation,1
2107,Female,22,1.75,133.74,yes,yes,3.0,3.0,Sometimes,no,2.01,no,1.34,0.599,Sometimes,Public_Transportation,1
2108,Female,23,1.75,133.69,yes,yes,3.0,3.0,Sometimes,no,2.05,no,1.41,0.646,Sometimes,Public_Transportation,1
2109,Female,24,1.74,133.35,yes,yes,3.0,3.0,Sometimes,no,2.85,no,1.14,0.586,Sometimes,Public_Transportation,1
2110,Female,24,1.74,133.47,yes,yes,3.0,3.0,Sometimes,no,2.86,no,1.03,0.714,Sometimes,Public_Transportation,1

Создадим регрессионный целевой признак BMI.

In [100]:
def class_to_regr(height:float, weight: float) -> float:
    result = weight/(np.square(height))
    return result

In [101]:
data_full['BMI'] = \
data_full.apply(lambda row: class_to_regr(row['Height'],row['Weight']),axis=1)

Закодируем остальные строковые показатели при помощи простого LabelEncoder.

In [102]:
categorical_features = [
    'Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 
    'SMOKE', 'SCC', 'CALC', 'MTRANS', 'Obesity'
]

# Инициализация LabelEncoder
label_encoders = {}

In [103]:
# Перекодировка категориальных признаков
for feature in categorical_features:
    if feature in data_full.columns:
        le = LabelEncoder()
        data_full[feature] = le.fit_transform(data_full[feature])
        label_encoders[feature] = le

Разделим выборку на тестовую и тренировочную.

In [104]:
X = data_full.drop(columns=['Obesity'])  # Let's say column 'target' is the target\class\label column
y = data_full['Obesity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    train_size=0.5, 
                                                    random_state=42)

In [105]:
data_train_to_csv=X_train
data_train_to_csv['Obesity']=y_train
data_train_to_csv

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI,Obesity
162,0,21,1.63,60.00,1,1,3.00,3.00,0,1,2.00,0,2.00,0.000,2,3,22.582709,0
2001,0,21,1.75,133.62,1,1,3.00,3.00,2,0,2.89,0,1.48,0.780,2,3,43.631020,1
1435,0,23,1.66,82.60,1,1,1.20,1.36,2,0,2.77,0,0.13,1.659,2,3,29.975323,1
649,0,22,1.59,44.24,0,0,3.00,1.70,1,0,2.55,0,1.10,0.000,3,3,17.499308,0
1280,1,26,1.81,106.04,1,1,3.00,3.00,2,0,2.86,0,1.81,0.680,2,3,32.367754,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,1,18,1.71,51.31,1,1,1.30,3.00,2,0,1.76,0,0.06,1.673,2,3,17.547280,0
717,1,18,1.85,59.21,1,1,2.71,3.74,2,0,2.03,0,2.01,0.614,3,0,17.300219,0
454,0,20,1.68,68.00,0,1,3.00,1.00,2,0,1.00,0,1.00,0.000,3,3,24.092971,0
264,1,18,1.87,67.00,1,1,3.00,3.00,1,0,3.00,1,1.00,1.000,2,0,19.159827,0
75,0,23,1.63,45.00,1,0,3.00,3.00,2,0,3.00,1,2.00,0.000,3,3,16.937032,0

In [106]:
data_test_to_csv=X_test
data_test_to_csv['Obesity']=y_test
data_test_to_csv

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI,Obesity
544,0,20,1.76,53.70,1,1,2.00,3.89,1,0,1.86,0,2.87,2.000,3,3,17.336002,0
1987,0,26,1.62,111.00,1,1,3.00,3.00,2,0,2.70,0,0.00,0.323,2,3,42.295382,1
420,1,18,1.85,60.00,1,1,3.00,4.00,2,0,2.00,1,2.00,0.000,2,0,17.531045,0
527,0,21,1.52,42.00,0,1,3.00,1.00,1,0,1.00,0,0.00,0.000,2,3,18.178670,0
196,1,22,1.75,74.00,1,0,2.00,3.00,2,0,2.00,0,1.00,2.000,2,1,24.163265,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,1,19,1.80,87.00,1,1,2.00,4.00,2,0,2.00,0,2.00,1.000,2,3,26.851852,1
1793,1,31,1.65,101.14,1,1,2.91,2.27,2,0,1.00,0,1.89,0.379,3,3,37.149679,1
73,1,19,1.85,65.00,1,0,2.00,3.00,2,0,3.00,0,2.00,1.000,2,1,18.991965,0
1711,1,29,1.76,113.50,1,1,2.32,3.00,2,0,2.16,0,0.00,1.465,2,0,36.641271,1
1103,1,19,1.70,79.68,1,0,2.74,2.16,2,0,1.09,0,0.11,0.004,3,3,27.570934,1

Для второй тестовой выборки возьмем все данные датасета.

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.99,
                                                    train_size=0.001, 
                                                    random_state=42)
data_test_to_csv2=X_test
data_test_to_csv2['Obesity']=y_test
data_test_to_csv2

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI,Obesity
544,0,20,1.76,53.70,1,1,2.00,3.89,1,0,1.86,0,2.87,2.000,3,3,17.336002,0
1987,0,26,1.62,111.00,1,1,3.00,3.00,2,0,2.70,0,0.00,0.323,2,3,42.295382,1
420,1,18,1.85,60.00,1,1,3.00,4.00,2,0,2.00,1,2.00,0.000,2,0,17.531045,0
527,0,21,1.52,42.00,0,1,3.00,1.00,1,0,1.00,0,0.00,0.000,2,3,18.178670,0
196,1,22,1.75,74.00,1,0,2.00,3.00,2,0,2.00,0,1.00,2.000,2,1,24.163265,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,0,17,1.58,44.41,0,1,2.74,3.00,2,0,2.31,0,2.24,1.593,2,3,17.789617,0
189,0,33,1.63,62.00,1,1,2.00,3.00,2,0,2.00,0,1.00,1.000,3,3,23.335466,0
1806,0,26,1.68,109.90,1,1,3.00,3.00,2,0,1.47,0,0.14,0.445,2,3,38.938492,1
975,0,18,1.73,75.97,1,1,2.93,3.00,2,0,2.21,0,1.00,0.797,1,3,25.383407,1
2047,0,19,1.68,127.43,1,1,3.00,3.00,2,0,1.44,0,1.43,0.662,2,3,45.149518,1

Запишем полученные датасеты в .csv и запишем в новые переменные (для чистоты эксперимента).

In [108]:
pd.DataFrame.to_csv(data_test_to_csv, './data/obesity_test.csv', sep=",", index=False)
pd.DataFrame.to_csv(data_train_to_csv, './data/obesity_train.csv', sep=",", index=False)
pd.DataFrame.to_csv(data_test_to_csv2, './data/obesity_test_full.csv', sep=",", index=False)